// GalaxyCut — Músicas e Áudios de Fundo para Shorts, Reels e TikTok
// 100% Instrumentais (sem vocais/falas), ideais para sobreposição de voz/narração.

import { StockItem } from "./stockClient";

export type ShortsVibe = "all" | "curiosity" | "lofi" | "comedy" | "tech" | "cinematic" | "gaming" | "relax";

export interface ShortsCategory {
  id: ShortsVibe;
  label: string;
  icon: string;
  description: string;
  searchTerms: string;
}

export const SHORTS_CATEGORIES: ShortsCategory[] = [
  {
    id: "all",
    label: "Todos os Shorts",
    icon: "📱",
    description: "Músicas de fundo neutras e versáteis para qualquer tipo de Short ou Reel",
    searchTerms: "instrumental background music beat ambient no vocals",
  },
  {
    id: "curiosity",
    label: "Curiosidades & Fatos",
    icon: "🕵️",
    description: "Storytelling, mistério leve, canais de fatos, ciência e teorias",
    searchTerms: "curiosity mystery ambient synth pulse documentary background instrumental",
  },
  {
    id: "lofi",
    label: "Lo-Fi & Calmo",
    icon: "☕",
    description: "Batidas suaves de Lo-Fi, café, vlogs, dicas e rotina",
    searchTerms: "lofi chill hip hop beat study relaxing instrumental no vocals",
  },
  {
    id: "comedy",
    label: "Cômico & Memes",
    icon: "🎭",
    description: "Clássicos virais de YouTubers (Kevin MacLeod, situações engraçadas, desafios)",
    searchTerms: "sneaky funny whimsical upbeat quirky comedy instrumental",
  },
  {
    id: "tech",
    label: "Tech & Tutoriais",
    icon: "💻",
    description: "Beats modernos limpos para reviews, IA, finanças e tutoriais rápidos",
    searchTerms: "tech modern clean minimal ambient beat corporate instrumental",
  },
  {
    id: "cinematic",
    label: "Tensão & Retenção",
    icon: "🎬",
    description: "Tensão contida, pulso rítmico e introduções para prender retenção",
    searchTerms: "cinematic ambient pulse soundtrack tension build instrumental",
  },
  {
    id: "gaming",
    label: "Gaming & Chiptune",
    icon: "🎮",
    description: "Trilhas 8-bit, ritmo retrô e fundo para cortes de jogos",
    searchTerms: "8bit chiptune retro game arcade beat instrumental",
  },
];

export interface CuratedShortsTrack extends StockItem {
  vibe: ShortsVibe;
  badge?: string;
  vibeLabel: string;
}

export const CURATED_SHORTS_TRACKS: CuratedShortsTrack[] = [
  // --- CURIOSIDADES & MISTÉRIO ---
  {
    id: "shorts-sneaky-snitch",
    title: "Sneaky Snitch (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/SneakySnitch",
    url: "https://archive.org/download/SneakySnitch/Sneaky%20Snitch.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 135,
    audio: true,
    vibe: "curiosity",
    badge: "🔥 Mais Usado",
    vibeLabel: "Curiosidades & Mistério",
  },
  {
    id: "shorts-as-i-figure",
    title: "As I Figure (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/As%20I%20Figure.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 216,
    audio: true,
    vibe: "curiosity",
    badge: "🕵️ Investigação",
    vibeLabel: "Curiosidades & Mistério",
  },
  {
    id: "shorts-apprehension",
    title: "Apprehension (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Apprehension.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 80,
    audio: true,
    vibe: "curiosity",
    badge: "⚡ Tensão Leve",
    vibeLabel: "Curiosidades & Mistério",
  },
  {
    id: "shorts-jamendo-mystic",
    title: "Dark Suspense Mystic Thriller",
    thumb: "https://usercontent.jamendo.com?type=album&id=1025611&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=1025611&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "Soundroll",
    duration: 120,
    audio: true,
    vibe: "curiosity",
    badge: "🌌 Atmosfera",
    vibeLabel: "Curiosidades & Fatos",
  },

  // --- CÔMICO & VIRAL ---
  {
    id: "shorts-monkeys-spinning",
    title: "Monkeys Spinning Monkeys (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/MonkeysSpinningMonkeys",
    url: "https://archive.org/download/MonkeysSpinningMonkeys/Monkeys%20Spinning%20Monkeys.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 125,
    audio: true,
    vibe: "comedy",
    badge: "⭐ Viral TikTok",
    vibeLabel: "Cômico & Memes",
  },
  {
    id: "shorts-amazing-plan",
    title: "Amazing Plan (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Amazing%20Plan.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 87,
    audio: true,
    vibe: "comedy",
    badge: "💡 Planos & Ideias",
    vibeLabel: "Cômico & Memes",
  },
  {
    id: "shorts-adventure-meme",
    title: "Adventure Meme (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Adventure%20Meme.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 101,
    audio: true,
    vibe: "comedy",
    badge: "🚀 Dinâmico",
    vibeLabel: "Cômico & Memes",
  },
  {
    id: "shorts-awkward-meeting",
    title: "Awkward Meeting (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Awkward%20Meeting.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 84,
    audio: true,
    vibe: "comedy",
    badge: "😅 Momentos Engraçados",
    vibeLabel: "Cômico & Memes",
  },

  // --- LO-FI & CALMO ---
  {
    id: "shorts-jamendo-autumn-lofi",
    title: "Autumn Wind (Lo-Fi Chill Beat)",
    thumb: "https://usercontent.jamendo.com?type=album&id=2037895&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=2037895&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "LoFi Chill Producer",
    duration: 142,
    audio: true,
    vibe: "lofi",
    badge: "☕ Café & Estudo",
    vibeLabel: "Lo-Fi & Calmo",
  },
  {
    id: "shorts-backed-vibes",
    title: "Backed Vibes Clean (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Backed%20Vibes%20Clean.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 228,
    audio: true,
    vibe: "lofi",
    badge: "🎷 Jazz & Relax",
    vibeLabel: "Lo-Fi & Calmo",
  },
  {
    id: "shorts-autumn-day",
    title: "Autumn Day (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Autumn%20Day.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 184,
    audio: true,
    vibe: "lofi",
    badge: "🍂 Acústico Suave",
    vibeLabel: "Lo-Fi & Calmo",
  },
  {
    id: "shorts-jamendo-stargazing",
    title: "Stargazing (Chillout Lo-Fi Background)",
    thumb: "https://usercontent.jamendo.com?type=album&id=2037897&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=2037897&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "Chillout Lab",
    duration: 150,
    audio: true,
    vibe: "lofi",
    badge: "✨ Relaxante",
    vibeLabel: "Lo-Fi & Calmo",
  },

  // --- TECH & TUTORIAIS ---
  {
    id: "shorts-jamendo-tech-ambient",
    title: "Abstract Ambient Tech Beat",
    thumb: "https://usercontent.jamendo.com?type=album&id=1678110&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=1678110&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "Tech Lab",
    duration: 115,
    audio: true,
    vibe: "tech",
    badge: "🤖 IA & Tech",
    vibeLabel: "Tech & Tutoriais",
  },
  {
    id: "shorts-jamendo-corporate",
    title: "Upbeat Corporate Background Beat",
    thumb: "https://usercontent.jamendo.com?type=album&id=1014546&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=1014546&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "Corporate Mood",
    duration: 130,
    audio: true,
    vibe: "tech",
    badge: "📈 Negócios & Dicas",
    vibeLabel: "Tech & Tutoriais",
  },
  {
    id: "shorts-b-roll",
    title: "B-Roll Neutral Beat (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/B-Roll.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 84,
    audio: true,
    vibe: "tech",
    badge: "🎬 B-Roll & Cortes",
    vibeLabel: "Tech & Tutoriais",
  },
  {
    id: "shorts-airport-lounge",
    title: "Airport Lounge (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Airport%20Lounge.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 307,
    audio: true,
    vibe: "tech",
    badge: "🎙️ Podcast & Vlog",
    vibeLabel: "Tech & Tutoriais",
  },

  // --- CINEMÁTICO & RETENÇÃO ---
  {
    id: "shorts-jamendo-epic-cinematic",
    title: "Cinematic Epic Emotional Background",
    thumb: "https://usercontent.jamendo.com?type=album&id=1026171&width=300",
    url: "https://prod-1.storage.jamendo.com/?trackid=1026171&format=mp32",
    provider: "Jamendo",
    license: "by",
    creator: "Cinematic Masters",
    duration: 155,
    audio: true,
    vibe: "cinematic",
    badge: "🔥 Retenção & Gancho",
    vibeLabel: "Tensão & Retenção",
  },
  {
    id: "shorts-black-vortex",
    title: "Black Vortex (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/BlackVortex.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 169,
    audio: true,
    vibe: "cinematic",
    badge: "⚡ Suspense Contido",
    vibeLabel: "Tensão & Retenção",
  },
  {
    id: "shorts-blue-feather",
    title: "Blue Feather Orchestral (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/BlueFeather.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 278,
    audio: true,
    vibe: "cinematic",
    badge: "🎻 Épico Suave",
    vibeLabel: "Tensão & Retenção",
  },

  // --- GAMING & RETRO ---
  {
    id: "shorts-bit-quest",
    title: "Bit Quest 8-Bit (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/Bit%20Quest.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 192,
    audio: true,
    vibe: "gaming",
    badge: "👾 8-Bit / Games",
    vibeLabel: "Gaming & Chiptune",
  },
  {
    id: "shorts-blip-stream",
    title: "Blip Stream Minimal (Kevin MacLeod)",
    thumb: "https://archive.org/services/img/Incompetech",
    url: "https://archive.org/download/Incompetech/mp3-royaltyfree/BlipStream.mp3",
    provider: "Incompetech (Kevin MacLeod)",
    license: "by",
    creator: "Kevin MacLeod",
    duration: 284,
    audio: true,
    vibe: "gaming",
    badge: "🕹️ Chiptune Beat",
    vibeLabel: "Gaming & Chiptune",
  },
];
